#!/usr/bin/env node

import JST from "../src/backend.js";
import {
	parent_dir,
	readlines
} from "sys";
import config from "config";

// const DIR = parent_dir(process.argv[1]);

const jst = new JST();
const [template_file, input_file, output_file] = process.argv.slice(2);

